# -*- coding: utf-8 -*-
"""Training_YOLO_obb_on_ShipRSImageNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WI0iXeFdA2yiJbr3Iui0y5aysU_LYMzl

Script to Train a Yolo-Obb Model on a Custom ShipRSImageNet Dataset
"""
-----------------------------
# Clone Ultralytics YOLOv8 repo (OBB version if available)
!pip install ultralytics
!pip install roboflow
!pip install --upgrade opencv-python

# Check GPU
!nvidia-smi

-----------------------------
# Loading Dataset From Roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="PUT_YOUR_API_KEY_HERE")
project = rf.workspace("vessels-tracking").project("ship-detection-thdbg")
version = project.version(2)
dataset = version.download("yolov8-obb")

-----------------------------
# Changing the classes from 50 original to 13 superclasses
import os

# Original → new class mapping
mapping = {
    0:10, 1:10, 2:10, 3:10, 4:10, 5:3, 6:1, 7:10, 8:1, 9:12,
    10:11, 11:10, 12:5, 13:0, 14:10, 15:9, 16:10, 17:10, 18:10,
    19:11, 20:11, 21:10, 22:8, 23:10, 24:2, 25:10, 26:10, 27:11,
    28:10, 29:10, 30:10, 31:1, 32:1, 33:10, 34:10, 35:10, 36:1,
    37:7, 38:11, 39:10, 40:11, 41:10, 42:11, 43:4, 44:10, 45:6,
    46:10, 47:10, 48:10, 49:10
}

# List of dataset splits
splits = ["train", "valid", "test"]

for split in splits:
    labels_dir = f"/content/Ship-Detection-2/{split}/labels"
    if not os.path.exists(labels_dir):
        print(f"Labels folder not found: {labels_dir}")
        continue
    for file in os.listdir(labels_dir):
        if file.endswith(".txt"):
            path = os.path.join(labels_dir, file)
            with open(path, "r") as f:
                lines = f.readlines()
            new_lines = []
            for line in lines:
                parts = line.strip().split()
                old_class = int(parts[0])
                if old_class in mapping:
                    parts[0] = str(mapping[old_class])
                    new_lines.append(" ".join(parts))
            with open(path, "w") as f:
                f.write("\n".join(new_lines))
    print(f"Updated labels in {split}/labels")

-----------------------------
# Updating the data.yaml file to match the new classes
import yaml

# Path to your existing YAML file
yaml_path = "/content/Ship-Detection-2/data.yaml"

# Define new Stage-1 maritime classes
new_classes = [
    "fishing_vessel",
    "cargo_ship",
    "tanker",
    "barge",
    "tugboat",
    "ferry",
    "yacht",
    "sailboat",
    "motorboat",
    "hovercraft",
    "warship",
    "auxiliary_ship",
    "dock"
]

# Load existing YAML
with open(yaml_path, "r") as f:
    data = yaml.safe_load(f)

# Update the names to the new 13 classes
data['names'] = {i: name for i, name in enumerate(new_classes)}

# Save updated YAML
with open(yaml_path, "w") as f:
    yaml.dump(data, f, default_flow_style=False)

print(f"Updated YAML saved at {yaml_path} with {len(new_classes)} classes.")

-----------------------------
# Mounting Drive to save Model Checkpoints
from google.colab import drive
drive.mount('/content/drive')

project_path = "/content/drive/MyDrive/ShipRS_YOLO_OBB_training"

-----------------------------
# Importing the Object Detection Model
from ultralytics import YOLO

# Load pretrained OBB model
model = YOLO("yolov8m-obb.pt")

-----------------------------
# Training the Model
# - task="obb" ensures oriented boxes are predicted
# - imgsz = 1024 → keep images square (good for OBB)
# - batch = 4 → GPU-friendly
model.train(
    data="/content/Ship-Detection-2/data.yaml",
    task="obb",
    epochs=100,
    imgsz=1024,
    batch=4,
    lr0=0.005,
    device=0,
    project=project_path,
    name="exp_obb",
    pretrained=True,
    patience=30
)

-----------------------------#back up code#-----------------------------
# RESUMING THE CODE AFTER THE GPU LIMIT FINISHED
from google.colab import drive
drive.mount('/content/drive')

from ultralytics import YOLO
model = YOLO("/content/drive/MyDrive/ShipRS_YOLO_OBB_training/exp_obb/weights/last.pt")

model.train(
    data="/content/Ship-Detection-2/data.yaml",
    task="obb",
    epochs=100,
    imgsz=1024,
    batch=4,
    device=0,
    project="/content/drive/MyDrive/ShipRS_YOLO_OBB_training",
    name="exp_obb",
    resume=True
)
-----------------------------#back up code#-----------------------------

-----------------------------
# Validate on validation set
val_results = model.val(
    data="/content/Ship-Detection-2/data.yaml",
    task="obb",
    imgsz=1024,
    batch=4,
    device=0
)

print("Validation Results:")
print(val_results)

-----------------------------
# Testing the model results on "unseen" test images
test_results = model.predict(
    source="/content/Ship-Detection-2/test/images",
    task="obb",
    imgsz=1024,
    batch=4,
    save=True,    # save predicted images (optional)
    conf=0.25
)

-----------------------------
# Copying prediction images to Drive
import shutil

src = "/content/runs/obb/predict"
dst = "/content/drive/MyDrive/ShipRS_YOLO_OBB_training/predictions"

os.makedirs(dst, exist_ok=True)
shutil.copytree(src, dst, dirs_exist_ok=True)

print("Predictions saved to:", dst)

-----------------------------
# Displaying predicted test images (optional)
from IPython.display import display
from PIL import Image
import glob

image_files = glob.glob("/content/runs/obb/predict/*.jpg")

for img_path in image_files[:20]:  # show first 20
    display(Image.open(img_path))

-----------------------------
# Test metrics
# Validate on the test set to get metrics
test_results = model.val(
    data="/content/Ship-Detection-2/data.yaml",  # YAML must have a 'test:' field
    task="obb",
    imgsz=1024,
    batch=4,
    split="test"  # Ensures it validates on the test split
)

-----------------------------
# Saving all the metrics to an excel file in DRIVE
import pandas as pd

# --- File to save metrics ---
excel_file = "/content/drive/MyDrive/ShipRS_YOLO_OBB_metrics.xlsx"

# --- VAL METRICS ---
val_overall = {
    "Model": "YOLOv8m-OBB",
    "Split": "Validation",
    "Precision": val_results.results_dict['metrics/precision(B)'],
    "Recall": val_results.results_dict['metrics/recall(B)'],
    "mAP50": val_results.results_dict['metrics/mAP50(B)'],
    "mAP50-95": val_results.results_dict['metrics/mAP50-95(B)']
}

# Per-class metrics
val_per_class = []
for i, name in val_results.names.items():
    val_per_class.append({
        "Model": "YOLOv8m-OBB",
        "Split": "Validation",
        "Class": name,
        "Precision": val_results.box.p[i],
        "Recall": val_results.box.r[i],
        "mAP50": val_results.box.ap50[i],
        "mAP50-95": val_results.box.ap[i],
        "Num_Targets": val_results.nt_per_class[i]
    })

val_overall_df = pd.DataFrame([val_overall])
val_per_class_df = pd.DataFrame(val_per_class)

# --- TEST METRICS ---
test_overall = {
    "Model": "YOLOv8m-OBB",
    "Split": "Test",
    "Precision": test_results.results_dict['metrics/precision(B)'],
    "Recall": test_results.results_dict['metrics/recall(B)'],
    "mAP50": test_results.results_dict['metrics/mAP50(B)'],
    "mAP50-95": test_results.results_dict['metrics/mAP50-95(B)']
}

# Per-class metrics
test_per_class = []
for i, name in test_results.names.items():
    test_per_class.append({
        "Model": "YOLOv8m-OBB",
        "Split": "Test",
        "Class": name,
        "Precision": test_results.box.p[i],
        "Recall": test_results.box.r[i],
        "mAP50": test_results.box.ap50[i],
        "mAP50-95": test_results.box.ap[i],
        "Num_Targets": test_results.nt_per_class[i]
    })

test_overall_df = pd.DataFrame([test_overall])
test_per_class_df = pd.DataFrame(test_per_class)

# --- SAVE TO EXCEL ---
with pd.ExcelWriter(excel_file, engine="openpyxl") as writer:
    val_overall_df.to_excel(writer, sheet_name="Val_Overall", index=False)
    val_per_class_df.to_excel(writer, sheet_name="Val_Per_Class", index=False)
    test_overall_df.to_excel(writer, sheet_name="Test_Overall", index=False)
    test_per_class_df.to_excel(writer, sheet_name="Test_Per_Class", index=False)

print(f"Validation and test metrics saved to {excel_file}")

-----------------------------
# Save predictions in YOLO format
predictions = model.predict(
    source="/content/Ship-Detection-2/test/images",  # your test images
    save_txt=True,  # save raw labels for training
    save_conf=True, # save confidence scores (optional, helpful)
    project="/content/Ship-Detection-2/predictions",
    name="test_predictions",
    exist_ok=True
)

-----------------------------
# Additing test images and labels for iterative dataset improvement
# Your project path in Drive
project_path = "/content/drive/MyDrive/ShipRS_YOLO_OBB_training"

# Predictions (labels only)
pred_labels = "/content/Ship-Detection-2/predictions/test_predictions/labels"

# Original test images
test_images = "/content/Ship-Detection-2/test/images"

# Destination folder in Drive
dst = os.path.join(project_path, "test_predictions_IDI")

# Create destination folder
os.makedirs(dst, exist_ok=True)

shutil.copytree(pred_labels, os.path.join(dst, "labels"), dirs_exist_ok=True)

shutil.copytree(test_images, os.path.join(dst, "images"), dirs_exist_ok=True)
