# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHEkQ974izf1ncLa-WwcgiZbsITEPWuw
"""

# Uploading the images and csv image metadata
from google.colab import drive
drive.mount('/content/drive')

!unzip "/content/drive/MyDrive/Images.zip" -d /content/Images

# Uploading the best.pt model weights
from google.colab import files
uploaded = files.upload()

!unzip "/content/YOLO26-obb_V1best.zip" -d /content

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

from ultralytics import YOLO
model_path = "/content/best.pt" # Add the path to the model here
model = YOLO(model_path)

test_images = "/content/Images/Images"

test_results = model.predict(
    source=test_images,
    task = "obb",
    imgsz=1024,
    batch=4,
    save=True,
    save_txt=True,
    save_conf=True,
)

# DISPLAYING RESULTS OF MODEL PREDICTION
import os
from IPython.display import display, Image

pred_dir = "/content/runs/obb/predict"

for img_file in sorted(os.listdir(pred_dir))[0:20]:
    if img_file.lower().endswith((".jpg", ".png")):
        display(Image(filename=os.path.join(pred_dir, img_file)))

# DOWNLOADING IMAGES AND LABELS FOR ITERATIVE DATASET IMPROVEMENT
import os
import shutil

# Source directories
src_images = "/content/Images/Images"
src_labels = "/content/runs/obb/predict/labels"

# Destination directories for Roboflow-ready dataset
dst_base = "/content/TRINIDAD_LABELS_ROBOFLOW_READY_CLEAN"
dst_images = os.path.join(dst_base, "images")
dst_labels = os.path.join(dst_base, "labels")

os.makedirs(dst_images, exist_ok=True)
os.makedirs(dst_labels, exist_ok=True)

count = 0

# Build a map of original images (base name -> filename)
orig_files_map = {os.path.splitext(f)[0]: f for f in os.listdir(src_images) if f.lower().endswith((".jpg", ".png", ".jpeg"))}

# Loop over label files (only images with detections)
for label_file in os.listdir(src_labels):
    base = os.path.splitext(label_file)[0]  # base filename without extension

    # Check if the original image exists
    if base in orig_files_map:
        img_path = os.path.join(src_images, orig_files_map[base])
        label_path = os.path.join(src_labels, label_file)

        # Copy image and label to the destination
        shutil.copy(img_path, os.path.join(dst_images, orig_files_map[base]))
        shutil.copy(label_path, os.path.join(dst_labels, label_file))

        count += 1
    else:
        print(f"Skipping {base}: image not found in source folder")

print(f"Copied {count} images and labels to {dst_base}")

# CREATING A CLASSES.TXT
classes = [
'auxiliary_ship',
'barge',
'cargo_ship',
'dock',
'ferry',
'fishing_vessel',
'hovercraft',
'motorboat',
'sailboat',
'tanker',
'tugboat',
'warship',
'yacht'
]

with open(os.path.join(dst_base, "classes.txt"), "w") as f:
    for c in classes:
        f.write(c + "\n")

print("classes.txt created")

import shutil

base_out = "/content/TRINIDAD_LABELS_ROBOFLOW_READY_CLEAN"

shutil.make_archive("/content/TRINIDAD_LABELS_ROBOFLOW_READY_CLEAN", "zip", base_out)

from google.colab import files
files.download("/content/TRINIDAD_LABELS_ROBOFLOW_READY_CLEAN.zip")

import os
import pandas as pd
import geopandas as gpd
from shapely.geometry import Polygon
import math

# -----------------------------
# Paths
# -----------------------------
labels_dir = "/content/runs/obb/predict/labels"
metadata_csv = "/content/Images/Images/tile_metadata.csv"
output_shp = "/content/vessel_detections_clean_take2.shp"

# -----------------------------
# Settings
# -----------------------------
img_size = 640
zoom = 19

class_map = {
    0: 'auxiliary_ship',
    1: 'barge',
    2: 'cargo_ship',
    3: 'dock',
    4: 'ferry',
    5: 'fishing_vessel',
    6: 'hovercraft',
    7: 'motorboat',
    8: 'sailboat',
    9: 'tanker',
    10: 'tugboat',
    11: 'warship',
    12: 'yacht'
}

# -----------------------------
# Load metadata
# -----------------------------
meta = pd.read_csv(metadata_csv)

meta_lookup = {}
for _, row in meta.iterrows():
    fname = os.path.basename(row["filename"])
    parts = fname.replace(".png","").split("_")
    site = parts[2]
    tile_id = parts[-1]
    key = f"{site}_{tile_id}"
    meta_lookup[key] = row

# -----------------------------
# Projection helpers
# -----------------------------
EARTH_RADIUS = 6378137

def latlon_to_mercator(lat, lon):
    x = EARTH_RADIUS * math.radians(lon)
    y = EARTH_RADIUS * math.log(math.tan(math.pi/4 + math.radians(lat)/2))
    return x, y

def mercator_to_latlon(x, y):
    lon = math.degrees(x / EARTH_RADIUS)
    lat = math.degrees(2 * math.atan(math.exp(y / EARTH_RADIUS)) - math.pi/2)
    return lat, lon

def polygon_to_latlon(coords, center_lat, center_lon):
    coords = [min(max(c, 0.0), 1.0) for c in coords]

    center_x, center_y = latlon_to_mercator(center_lat, center_lon)

    initial_resolution = 2 * math.pi * EARTH_RADIUS / 256
    resolution = initial_resolution / (2 ** zoom)
    half_size = img_size / 2

    lons, lats = [], []
    for i in range(0, len(coords), 2):
        dx = (coords[i] * img_size - half_size) * resolution
        dy = (coords[i+1] * img_size - half_size) * resolution

        mx = center_x + dx
        my = center_y - dy

        lat, lon = mercator_to_latlon(mx, my)
        lats.append(lat)
        lons.append(lon)

    return Polygon(zip(lons, lats))

# -----------------------------
# Parse YOLO labels
# -----------------------------
records = []

for file in os.listdir(labels_dir):
    if not file.endswith(".txt"):
        continue

    parts = file.replace(".txt","").split("_")
    site = parts[2]
    tile_id = parts[-1]
    key = f"{site}_{tile_id}"

    if key not in meta_lookup:
        print(f"No metadata for {file}")
        continue

    meta_row = meta_lookup[key]
    center_lat = meta_row["center_lat"]
    center_lon = meta_row["center_lon"]

    with open(os.path.join(labels_dir, file)) as f:
        lines = f.readlines()

    for line in lines:
        parts = line.strip().split()

        # EXPECT: class + 8 coords + confidence
        if len(parts) < 10:
            continue

        try:
            parts = list(map(float, parts))

            cls_id = int(parts[0])
            coords = parts[1:9]
            conf = parts[9]

            polygon = polygon_to_latlon(coords, center_lat, center_lon)

            records.append({
                "geometry": polygon,
                "class_id": cls_id,
                "class_name": class_map.get(cls_id, "unknown"),
                "confidence": conf,
                "site": site,
                "tile_id": tile_id
            })

        except Exception as e:
            print(f"Error in {file}: {e}")

# -----------------------------
# Create GeoDataFrame
# -----------------------------
gdf = gpd.GeoDataFrame(records, geometry="geometry", crs="EPSG:4326")

print("Before filtering:", len(gdf))

# -----------------------------
# 🔥 Confidence filtering (IMPORTANT)
# -----------------------------
gdf = gdf[gdf["confidence"] > 0.25]

print("After confidence filter:", len(gdf))

# -----------------------------
# 🔥 Spatial NMS (FIXED with projection)
# -----------------------------

# 🔥 Reproject to meters
gdf_proj = gdf.to_crs(epsg=3857)

# Compute area correctly
gdf_proj["area"] = gdf_proj.geometry.area

# Sort properly
gdf_proj = gdf_proj.sort_values(by=["area", "confidence"], ascending=[False, False])

kept = []
removed = set()

for i, row_i in gdf_proj.iterrows():
    if i in removed:
        continue

    geom_i = row_i.geometry
    kept.append(i)

    for j, row_j in gdf_proj.iterrows():
        if j == i or j in removed:
            continue

        geom_j = row_j.geometry

        if not geom_i.intersects(geom_j):
            continue

        inter = geom_i.intersection(geom_j).area
        union = geom_i.union(geom_j).area
        iou = inter / union if union != 0 else 0

        # 🔥 duplicate vessels
        if iou > 0.4:
            removed.add(j)

        # 🔥 edge fragments
        elif inter / min(geom_i.area, geom_j.area) > 0.7:
            removed.add(j)

# Keep clean detections
gdf_clean = gdf_proj.loc[kept].copy()

# 🔥 BACK to lat/lon
gdf_clean = gdf_clean.to_crs(epsg=4326)

print("After NMS:", len(gdf_clean))

# -----------------------------
# Save shapefile
# -----------------------------
gdf_clean.to_file(output_shp)

print(f"Saved: {output_shp}")

from google.colab import files
import os
import glob

# Folder where your shapefile is saved
shapefile_dir = "/content"
shapefile_base = "vessel_detections_clean_take2"

# List all shapefile components
shapefile_files = glob.glob(os.path.join(shapefile_dir, shapefile_base + ".*"))

# Download each file
for file in shapefile_files:
    files.download(file)