# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPS8-iXR9yZAVW5Hk_7DJaaW51Im-zLp
"""
# Python script created by Sofiya Tumanova
# This script can be used for testing a trained model on new imagery, visualizing the detection results, 
#        and creating an images and labels folder ready for iterative dataset improvement in Roboflow

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

from ultralytics import YOLO

model_path = "/content/drive/MyDrive/yolo_ship_phase1_training_version2/yolov8m_obb_phase18/weights/best.pt"
model = YOLO(model_path)

!unzip "/content/drive/MyDrive/RF_Test_Images.zip" -d /content/RF_Test_Images

test_images = "/content/RF_Test_Images/RF_Test_Images"

test_results = model.predict(
    source=test_images,
    task="obb",
    imgsz=1024,
    batch=4,
    conf=0.25,
    save=True,       # save images with boxes
    save_txt=True    # save predicted labels as .txt
)

results = model.predict(
    source=test_images,
    task="obb",
    imgsz=1024,
    batch=4,
    conf=0.25,
    iou=0.25,
    agnostic_nms=True,
    save_txt=True,   # 👈 THIS is the key
    save=True
)

import os
from IPython.display import display, Image

pred_dir = "/content/runs/obb/predict"

for img_file in sorted(os.listdir(pred_dir))[0:20]:
    if img_file.lower().endswith((".jpg", ".png")):
        display(Image(filename=os.path.join(pred_dir, img_file)))

import os
from IPython.display import display, Image

pred_dir = "/content/runs/obb/predict"
label_dir = os.path.join(pred_dir, "labels")
fishing_class_id = "0"  # class ID for fishing vessel

# Get all label files
label_files = sorted(os.listdir(label_dir))

for label_file in label_files:
    label_path = os.path.join(label_dir, label_file)

    # Check if the label file contains any fishing vessels
    with open(label_path) as f:
        if any(line.startswith(fishing_class_id + " ") for line in f):
            # Map label file to predicted image
            img_name = label_file.replace(".txt", ".jpg")
            img_path = os.path.join(pred_dir, img_name)

            if os.path.exists(img_path):
                display(Image(filename=img_path))

from PIL import Image
import os, shutil

src_images = "/content/RF_Test_Images/RF_Test_Images"
src_labels = "/content/runs/obb/predict/labels"

dst_base = "/content/678_roboflow_ready"
dst_images = os.path.join(dst_base, "images")
dst_labels = os.path.join(dst_base, "labels")

os.makedirs(dst_images, exist_ok=True)
os.makedirs(dst_labels, exist_ok=True)

# Convert BMP -> JPG
for f in os.listdir(src_images):
    if f.lower().endswith(".bmp"):
        img_path = os.path.join(src_images, f)
        img = Image.open(img_path).convert("RGB")
        jpg_name = os.path.splitext(f)[0] + ".jpg"
        img.save(os.path.join(dst_images, jpg_name), "JPEG")

# Copy labels
for f in os.listdir(src_labels):
    if f.endswith(".txt"):
        shutil.copy(os.path.join(src_labels, f), dst_labels)

print("JPG images and OBB labels prepared for Roboflow.")

import shutil

base_out = "/content/678_roboflow_ready"

shutil.make_archive("/content/678_roboflow_ready", "zip", base_out)

from google.colab import files
files.download("/content/678_roboflow_ready.zip")

import shutil
import os

folder = "/content/runs"

if os.path.exists(folder):
    shutil.rmtree(folder)
    print("Deleted old roboflow_ready folder.")
else:
    print("roboflow_ready folder does not exist.")

!zip -r original_687_test_results.zip /content/runs/obb/predict

from google.colab import files
files.download("/content/original_687_test_results.zip")

#------------------------------------------------------------------------

from google.colab import files
uploaded = files.upload()

import os
from ultralytics import YOLO

# Load your trained model
model = YOLO("/content/drive/MyDrive/ShipRS_YOLO_OBB_training/exp_obb/weights/best.pt")  # replace with your actual path

# Folder containing uploaded images
test_images_folder = "/content/"

# Make a list of image files (only png/jpg/jpeg)
test_images = [
    os.path.join(test_images_folder, f)
    for f in os.listdir(test_images_folder)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
]

# Run prediction on all images
results = model.predict(
    source=test_images,
    task="obb",
    imgsz=1024,
    conf=0.5,
    save=True,       # save images with predicted boxes
    save_txt=True    # save labels
)

import os
from IPython.display import display, Image

# Prediction folder
pred_dir = "/content/runs/obb/predict2"

# List all image files in the folder
image_files = [f for f in os.listdir(pred_dir) if f.lower().endswith((".jpg", ".png", ".jpeg"))]

# Display each image
for img_file in sorted(image_files):
    img_path = os.path.join(pred_dir, img_file)
    display(Image(filename=img_path))
