# -*- coding: utf-8 -*-
"""yolo26m-obb-1stversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYBac5ZJPYcPYAiAy4fHgPpZ3jtWHEI5

Script to train a YOLO 26 model on a custom dataset of vessels (13 generic classes)
"""

from google.colab import drive
drive.mount('/content/drive')

PROJECT_DIR = "/content/drive/MyDrive/yolo26_phase1_training_v1"
!nvidia-smi

!pip install -U ultralytics roboflow

!pip install tensorboard

from roboflow import Roboflow
rf = Roboflow(api_key="INSERT_API_KEY_HERE")
project = rf.workspace("vessels-tracking").project("ship-detection-2-evz92")
version = project.version(2)   # get most recent
dataset = version.download("yolov8-obb")

from ultralytics import YOLO

model = YOLO("yolo26m-obb.pt")  # pretrained on DOTA-style OBB

model.train(
    data="/content/Ship-Detection-2-2/data.yaml",
    task="obb",

    # Core training
    epochs=120,
    imgsz=1024,
    batch=4,            # reduce to 2 if OOM
    device=0,
    save_period=10,

    # Optimization
    lr0=1e-3,
    lrf=0.01,
    warmup_epochs=3,
    weight_decay=5e-4,

    # Geometry robustness
    scale=0.3,
    translate=0.05,
    degrees=180,

    # Photometric robustness (cross-sensor safe)
    hsv_h=0.015,        # small hue shift
    hsv_s=0.5,          # slightly reduced from default
    hsv_v=0.4,          # brightness variation

    # Noise & blur robustness
    # (Ultralytics auto-adds mild blur occasionally)
    flipud=0.5,         # vertical flip (satellite safe)
    fliplr=0.5,         # horizontal flip

    # Explicitly disabled for stability
    mosaic=0.0,
    mixup=0.0,

    # Label smoothing helps reduce duplicate detections
    label_smoothing=0.05,

    # Training control
    patience=30,
    pretrained=True,

    # Save to Google Drive
    project=PROJECT_DIR,
    name="yolo26m_obb_phase1"
)

# RESUMING training after session was stopped
from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/yolo26_phase1_training_v1/yolo26m_obb_phase12/weights/last.pt")
model.train(resume=True, device=0)

# Validate on validation set
val_results = model.val(
    data="/content/Ship-Detection-2-2/data.yaml",
    task="obb",
    imgsz=1024,
    batch=4,
    device=0
)

print("Validation Results:")
print(val_results)

# Testing the model results on "unseen" test images
test_results = model.predict(
    source="/content/Ship-Detection-2-2/test/images",
    task="obb",
    imgsz=1024,
    batch=4,
    save=True,      # save predicted images (optional)
    save_conf=True,
    conf=0.25
)

# Viewing Prediction Images
from IPython.display import display
from PIL import Image
import glob

image_files = glob.glob("/content/runs/obb/predict/*.jpg")

for img_path in image_files[:20]:  # show first 20
    display(Image.open(img_path))

# Validate on the TEST SET to get metrics
test_results = model.val(
    data="/content/Ship-Detection-2-2/data.yaml",  # YAML must have a 'test:' field
    task="obb",
    imgsz=1024,
    batch=4,
    split="test"  # Ensures it validates on the test split
)

# Adding Val and Test Metrics to the same excel file to compare models
import pandas as pd
from pathlib import Path

# --- File to save metrics ---
excel_file = "/content/drive/MyDrive/ShipRS_YOLO_OBB_training/ShipRS_YOLO_OBB_metrics.xlsx"

MODEL_NAME = "ShipRS_YOLO26_OBB_V1"   # <- change per experiment


# ---------- Helper function ----------
def append_to_sheet(df_new, sheet_name):
    if Path(excel_file).exists():
        try:
            df_old = pd.read_excel(excel_file, sheet_name=sheet_name)
            return pd.concat([df_old, df_new], ignore_index=True)
        except ValueError:
            return df_new
    return df_new


# ---------- VAL METRICS ----------
val_overall = {
    "Model": MODEL_NAME,
    "Split": "Validation",
    "Precision": val_results.results_dict['metrics/precision(B)'],
    "Recall": val_results.results_dict['metrics/recall(B)'],
    "mAP50": val_results.results_dict['metrics/mAP50(B)'],
    "mAP50-95": val_results.results_dict['metrics/mAP50-95(B)']
}

val_per_class = []
for i, name in val_results.names.items():
    val_per_class.append({
        "Model": MODEL_NAME,
        "Split": "Validation",
        "Class": name,
        "Precision": val_results.box.p[i],
        "Recall": val_results.box.r[i],
        "mAP50": val_results.box.ap50[i],
        "mAP50-95": val_results.box.ap[i],
        "Num_Targets": val_results.nt_per_class[i]
    })

val_overall_df = append_to_sheet(pd.DataFrame([val_overall]), "Val_Overall")
val_per_class_df = append_to_sheet(pd.DataFrame(val_per_class), "Val_Per_Class")


# ---------- TEST METRICS ----------
test_overall = {
    "Model": MODEL_NAME,
    "Split": "Test",
    "Precision": test_results.results_dict['metrics/precision(B)'],
    "Recall": test_results.results_dict['metrics/recall(B)'],
    "mAP50": test_results.results_dict['metrics/mAP50(B)'],
    "mAP50-95": test_results.results_dict['metrics/mAP50-95(B)']
}

test_per_class = []
for i, name in test_results.names.items():
    test_per_class.append({
        "Model": MODEL_NAME,
        "Split": "Test",
        "Class": name,
        "Precision": test_results.box.p[i],
        "Recall": test_results.box.r[i],
        "mAP50": test_results.box.ap50[i],
        "mAP50-95": test_results.box.ap[i],
        "Num_Targets": test_results.nt_per_class[i]
    })

test_overall_df = append_to_sheet(pd.DataFrame([test_overall]), "Test_Overall")
test_per_class_df = append_to_sheet(pd.DataFrame(test_per_class), "Test_Per_Class")


# ---------- SAVE BACK ----------
with pd.ExcelWriter(excel_file, engine="openpyxl", mode="w") as writer:
    val_overall_df.to_excel(writer, sheet_name="Val_Overall", index=False)
    val_per_class_df.to_excel(writer, sheet_name="Val_Per_Class", index=False)
    test_overall_df.to_excel(writer, sheet_name="Test_Overall", index=False)
    test_per_class_df.to_excel(writer, sheet_name="Test_Per_Class", index=False)

print(f"Metrics appended to {excel_file}")

# Downloading Model Weights Locally
weights_path = "/content" # Change this to model path
zip_path = "/content/ShipRS_YOLO_OBB_V2_best_weights.zip" # Change this name

import zipfile
import os

with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
    zipf.write(weights_path, arcname=os.path.basename(weights_path))

print(f"Zipped to: {zip_path}")

from google.colab import files

files.download(zip_path)

# Zipping and downloading the entire experiment folder locally
import zipfile
import os

# --- Paths ---
folder_to_zip = "/content/drive/MyDrive/yolo26_phase1_training_v1/yolo26m_obb_phase12" # CHANGE THIS
zip_output_path = "/content/yolo26m_obb_phase1.zip"  # CHANGE THIS NAME

# --- Create the zip ---
with zipfile.ZipFile(zip_output_path, "w", zipfile.ZIP_DEFLATED) as zipf:
    for root, _, files in os.walk(folder_to_zip):
        for file in files:
            full_path = os.path.join(root, file)
            # Use relative path inside the zip
            relative_path = os.path.relpath(full_path, folder_to_zip)
            zipf.write(full_path, arcname=relative_path)

print(f"Folder zipped successfully to: {zip_output_path}")

from google.colab import files
files.download(zip_output_path)

import shutil

shutil.rmtree("/content/Ship-Detection-2-1")