# -*- coding: utf-8 -*-
"""yolov8m-obb-2nd-version.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJWvS_VkGhw2OKEwSK6vzMgo9jHDGn2l

Custom yolov8m-obb model based on ShipRSImageNet dataset combined with Caribbean vessel images (640 & 930)
"""
# This script contains the training, validation, and testing code for a Phase 1 version 2 model to detect vessels from satellite imagery.

from google.colab import drive
drive.mount('/content/drive')

PROJECT_DIR = "/content/drive/MyDrive/yolo_ship_phase1_training_version2"
!nvidia-smi

!pip install -U ultralytics roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="ENTER_API_KEY_HERE")
project = rf.workspace("vessels-tracking").project("ship-detection-2-evz92")
version = project.version(1)
dataset = version.download("yolov8-obb")

from ultralytics import YOLO

model = YOLO("yolov8m-obb.pt")  # pretrained on DOTA-style OBB

model.train(
    data="/content/Ship-Detection-2-1/data.yaml",
    task="obb",

    # Core training
    epochs=120,
    imgsz=1024,       # keep large so small ships are still visible
    batch=4,          # adjust to 2 if OOM
    device=0,

    # Optimization
    lr0=1e-3,
    lrf=0.01,
    warmup_epochs=3,

    # Geometry robustness
    # multi_scale=False

    # Satellite-friendly color jitter
    hsv_h=0.015,
    hsv_s=0.7,
    hsv_v=0.4,

    # Training control
    patience=30,
    pretrained=True,

    # Oversample small images
    fraction=1.0,      # slight oversample for all, plus duplicated small images

    # 🔑 SAVE TO GOOGLE DRIVE
    project=PROJECT_DIR,
    name="yolov8m_obb_phase1"
)

from ultralytics import YOLO

checkpoint = "/content/drive/MyDrive/yolo_ship_phase1_training_version2/yolov8m_obb_phase18/weights/last.pt"

model = YOLO(checkpoint)

model.train(
    resume=True,

)

# Validate on validation set
val_results = model.val(
    data="/content/Ship-Detection-2-1/data.yaml",
    task="obb",
    imgsz=1024,
    batch=4,
    device=0
)

print("Validation Results:")
print(val_results)

# Testing the model results on "unseen" test images
test_results = model.predict(
    source="/content/Ship-Detection-2-1/test/images",
    task="obb",
    imgsz=1024,
    batch=4,
    save=True,      # save predicted images (optional)
    save_conf=True,
    conf=0.25
)

# Copying prediction images to Drive
import shutil
import os

src = "/content/runs/obb/predict"
dst = "/content/drive/MyDrive/yolo_ship_phase1_training_version2/predictions"

os.makedirs(dst, exist_ok=True)
shutil.copytree(src, dst, dirs_exist_ok=True)

print("Predictions saved to:", dst)

from IPython.display import display
from PIL import Image
import glob

image_files = glob.glob("/content/runs/obb/predict/*.jpg")

for img_path in image_files[:20]:  # show first 20
    display(Image.open(img_path))

# Test metrics
# Validate on the test set to get metrics
test_results = model.val(
    data="/content/Ship-Detection-2-1/data.yaml",  # YAML must have a 'test:' field
    task="obb",
    imgsz=1024,
    batch=4,
    split="test"  # Ensures it validates on the test split
)

# !!!! Maybe add to the same excel file as previously created!
# Saving all the metrics to an excel file in DRIVE
import pandas as pd

# --- File to save metrics ---
excel_file = "/content/drive/MyDrive/yolo_ship_phase1_training_version2/all_metrics.xlsx"

# --- VAL METRICS ---
val_overall = {
    "Model": "YOLOv8m-OBB",
    "Split": "Validation",
    "Precision": val_results.results_dict['metrics/precision(B)'],
    "Recall": val_results.results_dict['metrics/recall(B)'],
    "mAP50": val_results.results_dict['metrics/mAP50(B)'],
    "mAP50-95": val_results.results_dict['metrics/mAP50-95(B)']
}

# Per-class metrics
val_per_class = []
for i, name in val_results.names.items():
    val_per_class.append({
        "Model": "YOLOv8m-OBB",
        "Split": "Validation",
        "Class": name,
        "Precision": val_results.box.p[i],
        "Recall": val_results.box.r[i],
        "mAP50": val_results.box.ap50[i],
        "mAP50-95": val_results.box.ap[i],
        "Num_Targets": val_results.nt_per_class[i]
    })

val_overall_df = pd.DataFrame([val_overall])
val_per_class_df = pd.DataFrame(val_per_class)

# --- TEST METRICS ---
test_overall = {
    "Model": "YOLOv8m-OBB",
    "Split": "Test",
    "Precision": test_results.results_dict['metrics/precision(B)'],
    "Recall": test_results.results_dict['metrics/recall(B)'],
    "mAP50": test_results.results_dict['metrics/mAP50(B)'],
    "mAP50-95": test_results.results_dict['metrics/mAP50-95(B)']
}

# Per-class metrics
test_per_class = []
for i, name in test_results.names.items():
    test_per_class.append({
        "Model": "YOLOv8m-OBB",
        "Split": "Test",
        "Class": name,
        "Precision": test_results.box.p[i],
        "Recall": test_results.box.r[i],
        "mAP50": test_results.box.ap50[i],
        "mAP50-95": test_results.box.ap[i],
        "Num_Targets": test_results.nt_per_class[i]
    })

test_overall_df = pd.DataFrame([test_overall])
test_per_class_df = pd.DataFrame(test_per_class)

# --- SAVE TO EXCEL ---
with pd.ExcelWriter(excel_file, engine="openpyxl") as writer:
    val_overall_df.to_excel(writer, sheet_name="Val_Overall", index=False)
    val_per_class_df.to_excel(writer, sheet_name="Val_Per_Class", index=False)
    test_overall_df.to_excel(writer, sheet_name="Test_Overall", index=False)
    test_per_class_df.to_excel(writer, sheet_name="Test_Per_Class", index=False)

print(f"Validation and test metrics saved to {excel_file}")

import pandas as pd
from pathlib import Path

# --- File to save metrics ---
excel_file = "/content/drive/MyDrive/ShipRS_YOLO_OBB_training/ShipRS_YOLO_OBB_metrics.xlsx"

MODEL_NAME = "ShipRS_YOLO_OBB_V2"   # <- change per experiment


# ---------- Helper function ----------
def append_to_sheet(df_new, sheet_name):
    if Path(excel_file).exists():
        try:
            df_old = pd.read_excel(excel_file, sheet_name=sheet_name)
            return pd.concat([df_old, df_new], ignore_index=True)
        except ValueError:
            return df_new
    return df_new


# ---------- VAL METRICS ----------
val_overall = {
    "Model": MODEL_NAME,
    "Split": "Validation",
    "Precision": val_results.results_dict['metrics/precision(B)'],
    "Recall": val_results.results_dict['metrics/recall(B)'],
    "mAP50": val_results.results_dict['metrics/mAP50(B)'],
    "mAP50-95": val_results.results_dict['metrics/mAP50-95(B)']
}

val_per_class = []
for i, name in val_results.names.items():
    val_per_class.append({
        "Model": MODEL_NAME,
        "Split": "Validation",
        "Class": name,
        "Precision": val_results.box.p[i],
        "Recall": val_results.box.r[i],
        "mAP50": val_results.box.ap50[i],
        "mAP50-95": val_results.box.ap[i],
        "Num_Targets": val_results.nt_per_class[i]
    })

val_overall_df = append_to_sheet(pd.DataFrame([val_overall]), "Val_Overall")
val_per_class_df = append_to_sheet(pd.DataFrame(val_per_class), "Val_Per_Class")


# ---------- TEST METRICS ----------
test_overall = {
    "Model": MODEL_NAME,
    "Split": "Test",
    "Precision": test_results.results_dict['metrics/precision(B)'],
    "Recall": test_results.results_dict['metrics/recall(B)'],
    "mAP50": test_results.results_dict['metrics/mAP50(B)'],
    "mAP50-95": test_results.results_dict['metrics/mAP50-95(B)']
}

test_per_class = []
for i, name in test_results.names.items():
    test_per_class.append({
        "Model": MODEL_NAME,
        "Split": "Test",
        "Class": name,
        "Precision": test_results.box.p[i],
        "Recall": test_results.box.r[i],
        "mAP50": test_results.box.ap50[i],
        "mAP50-95": test_results.box.ap[i],
        "Num_Targets": test_results.nt_per_class[i]
    })

test_overall_df = append_to_sheet(pd.DataFrame([test_overall]), "Test_Overall")
test_per_class_df = append_to_sheet(pd.DataFrame(test_per_class), "Test_Per_Class")


# ---------- SAVE BACK ----------
with pd.ExcelWriter(excel_file, engine="openpyxl", mode="w") as writer:
    val_overall_df.to_excel(writer, sheet_name="Val_Overall", index=False)
    val_per_class_df.to_excel(writer, sheet_name="Val_Per_Class", index=False)
    test_overall_df.to_excel(writer, sheet_name="Test_Overall", index=False)
    test_per_class_df.to_excel(writer, sheet_name="Test_Per_Class", index=False)

print(f"Metrics appended to {excel_file}")

weights_path = "/content/drive/MyDrive/yolo_ship_phase1_training_version2/yolov8m_obb_phase18/weights/best.pt"
zip_path = "/content/ShipRS_YOLO_OBB_V2_best_weights.zip"

import zipfile
import os

with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
    zipf.write(weights_path, arcname=os.path.basename(weights_path))

print(f"Zipped to: {zip_path}")

from google.colab import files

files.download(zip_path)

import zipfile
import os

# --- Paths ---
folder_to_zip = "/content/drive/MyDrive/yolo_ship_phase1_training_version2/yolov8m_obb_phase18"
zip_output_path = "/content/yolov8m_obb_phase18.zip"  # where the zip will be saved

# --- Create the zip ---
with zipfile.ZipFile(zip_output_path, "w", zipfile.ZIP_DEFLATED) as zipf:
    for root, _, files in os.walk(folder_to_zip):
        for file in files:
            full_path = os.path.join(root, file)
            # Use relative path inside the zip
            relative_path = os.path.relpath(full_path, folder_to_zip)
            zipf.write(full_path, arcname=relative_path)

print(f"Folder zipped successfully to: {zip_output_path}")

from google.colab import files
files.download(zip_output_path)
